import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
// import { AppSidebar } from "@/components/shared/AppSidebar"

// import AppLayout from "@/components/shared/AppLayout"
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Note-taking web app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
         <script src="https://unpkg.com/react-scan/dist/auto.global.js" async />
      </head>
      <body className={`${inter.className} antialiased`}>
          {children}
      </body>
    </html>
  );
}
